const main_url = 'http://localhost:3000/api'

export const register_api = main_url + '/auth/register'
export const user_verify_api = main_url + '/auth/user-verify'
export const resend_otp_api = main_url + '/auth/resend-otp'
export const login_api = main_url + '/auth/login'
export const contact_form_api = main_url + '/contactus/add'
export const home_api = main_url + '/home'
export const edit_profile_api = main_url + '/user/edit'

// category Api 
export const category_list_api = main_url + '/category/list'
export const category_add_api = main_url + '/category/add'
export const category_details_api = main_url + '/category/details'
export const category_edit_api = main_url + '/category/edit'
export const edit_user_address_api = main_url + '/user-address/edit'
export const user_profile_api = main_url + '/user/profile'
export const add_product = main_url + '/product/add'
export const get_All_blogs = main_url + '/blog/list'
export const product_list_ = main_url + '/product/get-all'
export const product_details_ = main_url + '/product/get-details'
export const product_edit_ = main_url + '/product/edit'
export const search_client_ = main_url + '/search'
export const wishlist_add_ = main_url + '/wishlist/add'
export const wishlist_list_get_ = main_url + '/wishlist/list'
export const wishlist_product_remove_ = main_url + '/wishlist/remover-product'
export const wishlist__remove_ = main_url + '/wishlist/remove-wishlist'
export const add__blog_ = main_url + '/blog/add'
export const blog_details = main_url + '/blog/details'
export const blog_edit = main_url + '/blog/edit'
export const blog_delete = main_url + '/blog/delete'
export const all_users = main_url + '/dashboard/user/list'
export const users_details_admin = main_url + '/dashboard/user/user-details'
export const users_detail_edit_by_admin = main_url + '/dashboard/user/edit'
export const contact_us_list_api = main_url + '/contactus/list'
export const contact_us_update_api = main_url + '/contactus/edit'
export const upload_image_api = main_url + '/upload_image'
export const create_order_api = main_url + '/order/add'
export const add_store_api = main_url + '/store/add'
export const store_details_api = main_url + '/store/details'
export const edit_store_api = main_url + '/store/edit'
export const list_store_api = main_url + '/store/list'
export const add_coupons_api = main_url + '/coupons/add'
// export const upload_image_api = main_url + '/get-one-user'

export const add_blog_category_api = main_url + '/blog-category/add'
export const blog_category_list_api = main_url + '/blog-category/list'
export const blog_category_edit_api = main_url + '/blog-category/edit'
export const blog_category_details_api = main_url + '/blog-category/details'
export const coupons_list_api = main_url + '/coupons/get'
export const edit_coupons_api = main_url + '/coupons/edit'
export const coupons_detail_api = main_url + '/coupons/detail'
export const order_list_api = main_url + '/order/list'


