const main_url = 'http://localhost:3000/api'

export const register_api = main_url + '/auth/register'
export const user_verify_api = main_url + '/auth/user-verify'
export const resend_otp_api = main_url + '/auth/resend-otp'
export const login_api = main_url + '/auth/login'
export const contact_form_api = main_url + '/contactus/add'
export const home_api = main_url + '/home'
export const edit_profile_api = main_url + '/user/edit'

// category Api 
export const category_list_api = main_url + '/category/list'
export const category_add_api = main_url + '/category/add'
export const category_details_api = main_url + '/category/details'
export const edit_user_address_api = main_url + '/user-address/edit'
export const user_profile_api = main_url + '/user/profile'
export const add_product = main_url + '/product/add'
export const get_All_blogs = main_url + '/blog'
export const product_list_ = main_url + '/product/get-all'
export const product_details_ = main_url + '/product/get-details'